name: R-CMD-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    ...

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pandoc

      - name: Install R package dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: |
          devtools::check()
        shell: Rscript {0}
